### ISSUE TITLE
Checkboxes and radio not working?

### ISSUE THREAD

**Issue by ghost** [html5cat/bootstrap-material-design#3] opened 2014-11-03 12:35 UTC
After adding the package, everything went material, but for some reason checkboxes and radio buttons don't show up at all, despite having the right classes (class="checkbox" for example) on the container divs. I'm using autoform for the actual forms, with boostrap 3 theme.

**Comment by stachrom** [comment] 2014-11-04 09:39
take a look at:  https://github.com/FezVrasta/bootstrap-material-design/issues/15

this explains why. 

regards roman

**Comment by ghost** [comment] 2014-11-04 09:47
Yeah, I found that, in the end. Has anyone found some kind of Meteor workaround for this? I tried calling $.material.checkbox() in Template.rendered, but that doesn't seem to work as $.material is undefined... (so I assume my approach is completely wrong)

**Comment by stachrom** [comment] 2014-11-04 10:00
What we need to do, is exchange the functionality from arrive.js. 

https://github.com/FezVrasta/bootstrap-material-design/blob/master/scripts/material.js#L120

**Comment by Amdingo** [comment] 2014-11-08 03:51
Add arrive.js to your project as the first file imported, you're missing the dependency?

Can't seem to find the same files that you did in your package...was going to fork but meh.

If you add arrive.js then the radios and checkboxes will work just fine.

**Comment by neopostmodern** [comment] 2014-11-09 13:23
Could someone outline how to include the `arrive.js` in Meteor?

**Comment by Amdingo** [comment] 2014-11-09 17:54
you can slap it in your lib, but I believe that the packages will load before that anyway.

Ideally html5cat would include the files that he used to build the package, and then I could fork it and include arrive.js and rebuild the package, or html5cat could go ahead and do that themselves and retain the functioning version on atmosphere.js.  I went looking through Fez's build and it looks like there are subtle differences that I don't want to attempt to recreate.

If you want to test it yourself to see the checkboxes working you can load up a project and then dive down to the package js and insert the entirety of arrive.js after the imports, and refresh your project within the browser.  Note that meteor reverifies and downloads the correct js which will override the changes that you made, and that you'll have to overwrite the file each time you want to see the functionality.  Seems like the only that doesn't work after including arrive.js is the flyaway text.

http://pastebin.com/C2PNF5BD

**Comment by html5cat** [comment] 2014-11-15 01:28
Latest version seems to have checkbox styled. Let me know if this needs more attention.

Thanks!

**Comment by ghost** [comment] 2014-11-17 09:30
I updated to 0.1.4, but checkboxes and radio buttons still don't work. I'm also using Autoform 4, if that helps.

**Comment by html5cat** [comment] 2014-11-18 08:24
@DigitalAndre could you through a reproduction case via http://meteorpad.com/ ?

**Comment by ghost** [comment] 2014-11-18 10:30
I can try - we have so many packages loaded in now that it's going to be hard to figure out what to include, and what not to... I'll try to make a "naked" Meteor app with mizzao:bootstrap-3 and bootstrap-material and see if it works, and backtrack from there...

**Comment by rhythnic** [comment] 2014-12-09 15:48
I tried adding arrive.js to the lib folder, but it threw an error:  HTMLElement not defined.  However, adding $.material.radio() to the template rendered function worked.

**Comment by dandv** [comment] 2014-12-15 15:28
Hey guys,

@html5cat asked me to help with integrating this theme with Meteor, so I've submitted [a PR](https://github.com/FezVrasta/bootstrap-material-design/pull/291) directly to @fezvrasta that will enable him to publish updates as he releases them. There is a pretty comprehensive [test suite](https://github.com/FezVrasta/bootstrap-material-design/pull/291/files#diff-6) so please let me know if you still see any problems (a screenshot would help).

You can already use the package [from Atmosphere](https://atmospherejs.com/fezvrasta/bootstrap-material-design):

```
meteor add fezvrasta:bootstrap-material-design
```

Thanks again to Yuri for making this theme available for Meteor and so popular.

**Comment by FezVrasta** [comment] 2014-12-15 15:43
merged, now I just need to figure out how it works :P

**Comment by dandv** [comment] 2014-12-15 15:57
:+1:  Thanks @FezVrasta :) Closing this - 

Everyone else, if there are further issues, please file a [ticket in FezVrasta's repo](https://github.com/FezVrasta/bootstrap-material-design/), and he'll helpfully add the `meteor` label.

**Comment by FezVrasta** [comment] 2014-12-15 16:04
I'll add the label and then someone will take care of it because I really really really don't know anything about this thing :yum:

**Comment by dandv** [comment] 2014-12-15 16:05
I will, [as the README says](https://github.com/FezVrasta/bootstrap-material-design/blob/master/meteor/README.md#issues) :)

**Closed as completed by FezVrasta** 2014-12-15 16:04 UTC

**Comment by dandv** [comment] 2014-12-15 16:06
BTW @DigitalAndre, the best-maintained Bootstrap package is the official community integration, [twbs:bootstrap](https://atmospherejs.com/twbs/bootstrap).

**Comment by FezVrasta** [comment] 2014-12-15 16:07
Added the label, and even a tiny symbol that should represent a meteor :|

![image](https://cloud.githubusercontent.com/assets/5382443/5439042/e405c348-847c-11e4-94b0-ec086895eac6.png)

Improvements are welcome ahahah

**Comment by dandv** [comment] 2014-12-15 16:30
# _M̹̥͉͎͝O̢͚̻͇S̖̳̻͔̘T͓͈͝ ҉̻̠͙̩̹̙̫A͞W̟̞̜̯̙E̪̫SƠ̺̜̲̩ͅͅM͕E͖̼̤͖̥̠̫ ̷̙̗̞͇̤͈̯Ḽ̡͚̦̗̦̺̪A̖̱̖ͅB͔̀E̥̳̹̩̟̱L̷̞͍ ͉̹̰̮F͏̳̞͖͕̳T͍̳͠Ẁ̦͎̱͓̯!̦̗̣_

**Comment by ghost** [comment] 2014-12-16 09:32
@dandv is that better than mizzao's? Only that one seems to come higher on atmo's search results, but maybe that's meaningless. (Bit of a Meteor noob here...) Thanks for the tips and all the help - I'll try with twbs:bootstrap and fezvrasta:bootstrap-material-design

**Comment by dandv** [comment] 2014-12-16 11:25
@DigitalAndre: [oh](https://github.com/twbs/bootstrap/pull/15376), [yes](https://github.com/mizzao/meteor-bootstrap-3/issues/14#issuecomment-64942535). @mizzao's package has more stars just because it's been there longer. twbs:bootstrap is as good as you can get.
